### ISSUE TITLE
[Quality of life] Cannon breach block places in the wrong rotation 

### ISSUE THREAD

**Issue by Abrams11IsBack** [Cannoneers-of-Create/CreateBigCannons#3]
![placement](https://user-images.githubusercontent.com/71346253/180494499-2a243190-387f-462c-9fe0-f2c0ed6db4b0.png)

**Comment by rbasamoyai** [comment]
Intended, use a wrench to configure the breech

Edit: did not notice the QOL designation, but my rationale is that it would allow for different placement of rotational input

Edit 2: might do axis aligned fuckery in the default state placement thingy so that it places horizontal by default, but again, vertical axis will remain
