### ISSUE TITLE
Light bug with Bronze sliding breech

### ISSUE THREAD

**Issue by Crabanutij** [Cannoneers-of-Create/CreateBigCannons#30]
Build a wall with theese and you'll see
Edited: other blocks seems dont have that problem
Version: **nightly-dc995e9**
_**dynamiclightsreforged-1.18.2_v1.3.3
rubidium_extras-1.18.2_v1.3.1
rubidium-0.5.2a**_
![2022-07-28_14 07 11](https://user-images.githubusercontent.com/109973204/181501165-834ce84f-b1ec-42df-a1b9-fe3810f7c2c3.png)
![2022-07-28_14 00 04](https://user-images.githubusercontent.com/109973204/181501173-f7dad67b-e8af-4978-89b9-82ebba35444f.png)

**Comment by rbasamoyai** [comment]
I've noticed this with the cast iron sliding breech as well - it's more subtle due to the black color.

I believe it has to do with Minecraft's lighting engine and its limitations with custom models. You could try using Forge's experimental lighting option, which can be turned on jn `forge-config.toml`, but I'm not sure if that will completely fix it, especially on contraptions.

**Comment by rbasamoyai** [comment]
Actually, I've noticed lighting erros with a multitude of my other blocks, so I'll try to remedy those as much as possible
