### ISSUE TITLE
Suggestion: get rid of yaw controller

### ISSUE THREAD

**Issue by AngelOfCreation** [Cannoneers-of-Create/CreateBigCannons#459]
I'm not even sure why the yaw controller exists. It just makes so much more sense to run the rotation directly into the cannon mount from below.

**Comment by rbasamoyai** [comment]
This is planned for a later version, but no clear implementation has been formulated yet. The reason why the yaw controller exists is because Create does not yet have a proper method for separate kinetic inputs into a single block. This is important for a single-block Cannon Mount that has both pitch and yaw input in the same block.

There are "hacky" ways to implement this that could probably be done. I have read on the Create discord that a kinetic rework is planned that would provide a much cleaner way to achieve the separate inputs required, but I am fine with a less sound implementation before any such rework is released.

**Comment by rbasamoyai** [comment]
Implemented in #712, #713, and #714.
